version: "3"
services:
  web:
    image: chatbot:latest
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "40135:5000"
    networks:
      - overlay
networks:
  overlay:
